75462 Webhook Authentication Rbac Jwt Token
UKHO/erp-facade pull request #12
Opened 2023-04-17 14:07 UTC by Shirin14926

Code changes-Authentication and Configuration

2023-04-20 14:07 UTC, jrippington approved these changes
Looks good!

2023-04-21 08:33 UTC, harshal11869 requested changes

2023-04-21 08:33 UTC, harshal11869 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/WebhookEndpoint.cs
> +            using (StreamReader r = new StreamReader(filePath))
```suggestion
            using (StreamReader streamReader = new StreamReader(filePath))
```

2023-04-21 08:49 UTC, Shirin14926 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/WebhookEndpoint.cs
> +            using (StreamReader r = new StreamReader(filePath))
done. thanks

2023-04-21 08:59 UTC, harshal11869 approved these changes
Looks Good. @Shirin14926 Thanks for fixing the review comments.

2023-04-21 10:09 UTC, jrippington approved these changes
Looks good, thanks!

2023-04-21 10:11 UTC, JiviteshT approved these changes
Approved to progress merge

2023-04-21 10:11 UTC, merged