WIP-145246 eliminate price information uos updated event
UKHO/erp-facade pull request #120
Opened 2024-03-11 14:04 UTC by MitaliSingh16

Eliminated the Unit of sale updated event and Price Change event to prevent pricing information from passing from SAP to ERP facade.
/erpfacade/priceinformation
/erpfacade/bulkpriceinformation
- Removed below Tables
  -unitpricechangeevents
  -pricechangemaste

- Modified below table - 
  -encevents
- Removed below Webjob 
    -PriceChangeEvent
    -Monitoring' 
- Cleanup webjob is modified.
- Also removed related FT's and UT's

2024-03-12 09:14 UTC, Sadha1501493 requested changes

2024-03-12 09:14 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/appsettings.json
> +    //"PriceChangePayloadFileName": "PriceChangeInput.JSON",
please remove commented code

2024-03-12 09:14 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/SAPXmlHelper.cs
> +            JsonPayloadHelper obj = jsonPayload;
Please keep it var only.

2024-03-13 09:52 UTC, MitaliSingh16 commented on tests/UKHO.ERPFacade.API.FunctionalTests/appsettings.json
> +    //"PriceChangePayloadFileName": "PriceChangeInput.JSON",
Done

2024-03-13 09:52 UTC, MitaliSingh16 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/SAPXmlHelper.cs
> +            JsonPayloadHelper obj = jsonPayload;
Done

2024-03-13 12:10 UTC, pravinvarade10801 approved these changes
LGTM

2024-03-13 13:10 UTC, Sadha1501493 approved these changes
LGTM

2024-03-14 12:59 UTC, Vishal14583 requested changes
Added few review comments.

2024-03-14 13:16 UTC, amogh14893 commented on Deployment/templates/continuous-testing.yml
> +  #     azureSubscription: "ERP-Facade-Dev-A.011.05.12"
Removed commented code

2024-03-14 13:31 UTC, MitaliSingh16 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/RoSXMLHelper.cs
> +        private static JsonInputRoSWebhookEvent s_jsonPayload;
done

2024-03-14 13:31 UTC, MitaliSingh16 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/JSONHelper.cs
> +        private static readonly string s_projectDir = Path.GetFullPath(Path.Combine(Environment.CurrentDirectory));
done

2024-03-14 13:48 UTC, Vishal14583 approved these changes
LGTM

2024-03-14 14:34 UTC, Vishal14583 approved these changes
LGTM

2024-03-15 08:51 UTC, jrippington approved these changes
Looks good

2024-03-15 08:51 UTC, merged