Vulnerabilities fix in pipeline
UKHO/erp-facade pull request #24
Opened 2023-05-04 08:16 UTC by Shirin14926

Vulnerabilities observed in dev when Nuget restore command was added.
We have suppressed few, few are resolved by updating stable versions of nuget packages.

2023-05-04 14:32 UTC, harshal11869 approved these changes
Looks Good.

2023-05-05 09:29 UTC, jrippington approved these changes
Looks good, thanks!

2023-05-05 09:54 UTC, martyn-fewtrell requested changes
I realise this is Symantec's but it would be good to be consistent with which version we are pinned to otherwise it looks like it is out of date and would need reviewing again

2023-05-05 09:54 UTC, martyn-fewtrell commented on NVDSuppressions.xml
> +        FSS is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App Service which will have the security patch applied.
FSS is pinned?

Assume ERP is 6.......

2023-05-05 09:54 UTC, martyn-fewtrell commented on NVDSuppressions.xml
> +        ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App Service which will have the security patch applied.
? ERP Facade is pinned to .Net core SDK > 6.0.101

2023-05-05 09:54 UTC, martyn-fewtrell commented on NVDSuppressions.xml
> +      This CVE applies to any .NET Core based application running on .NET Core 2.1.0-2.1.12, or .NET Core 2.2.0-2.2.6. FSS is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to
ERP Facade is pinned to .Net core SDK > 6.0.101

2023-05-05 09:54 UTC, martyn-fewtrell commented on NVDSuppressions.xml
> +    This applies to version of System.Net.Http as deployed as part of .Net core below 2.1.7 or 2.2.1. ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App
ERP Facade is pinned to .Net core SDK > 6.0.101

2023-05-05 09:54 UTC, martyn-fewtrell commented on NVDSuppressions.xml
> +    This CVE applies to .Net Core versions below 2.2.107 (runtime 2.2.5). ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App Service which will have the
ERP Facade is pinned to .Net core SDK > 6.0.101

2023-05-05 09:54 UTC, martyn-fewtrell commented on NVDSuppressions.xml
> +    This CVE only applies to .NetCore versions below 2.1.8 and 2.2.2. ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App Service which will have the sec
ERP Facade is pinned to .Net core SDK > 6.0.101

2023-05-05 10:26 UTC, Shirin14926 commented on NVDSuppressions.xml
> +    This CVE only applies to .NetCore versions below 2.1.8 and 2.2.2. ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App Service which will have the sec
Done, Thanks

2023-05-05 10:26 UTC, Shirin14926 commented on NVDSuppressions.xml
> +    This CVE applies to .Net Core versions below 2.2.107 (runtime 2.2.5). ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App Service which will have the
Done, Thanks

2023-05-05 10:26 UTC, Shirin14926 commented on NVDSuppressions.xml
> +    This applies to version of System.Net.Http as deployed as part of .Net core below 2.1.7 or 2.2.1. ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App
Done, Thanks

2023-05-05 10:27 UTC, Shirin14926 commented on NVDSuppressions.xml
> +      This CVE applies to any .NET Core based application running on .NET Core 2.1.0-2.1.12, or .NET Core 2.2.0-2.2.6. FSS is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to
Done, Thanks

2023-05-05 10:27 UTC, Shirin14926 commented on NVDSuppressions.xml
> +        ERP Facade is pinned to .Net core SDK > 3.1.408 which is not vunerable, and deployed to Azure App Service which will have the security patch applied.
Missed it, Thanks

2023-05-05 10:55 UTC, martyn-fewtrell approved these changes
Thanks you - Looks good

2023-05-05 11:30 UTC, merged