Feature/78581 scenario verification
UKHO/erp-facade pull request #27
Opened 2023-05-05 12:48 UTC by Sadha1501493

Branch has logic to verify XMLs of below 2 scenarios:
1. New cell Scenario
2. Cancel and replaced Scenario

2023-05-09 07:42 UTC, RaviK2233 approved these changes
Reviewed FT and looks good

2023-05-09 07:45 UTC, RaviK2233 reviewed
Hi @Sadha1501493 , some of the checks have failed. Could you please resolve them.

2023-05-10 10:36 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Model/JsonPayloadHelper.cs
> +    public class JsonPayloadHelper
This class is created for .json file deserialization. So, from maintenance perspective good to have in one file.
But still let me know if split is needed.

2023-05-11 07:38 UTC, jrippington requested changes
Thanks, please can you resolve the merge conflicts?

2023-05-11 12:43 UTC, jrippington approved these changes

2023-05-11 12:49 UTC, martyn-fewtrell approved these changes
Looks good

2023-05-11 12:49 UTC, merged