Added FT to test 500 error code for mock SAP API
UKHO/erp-facade pull request #28
Opened 2023-05-05 13:17 UTC by prashantmgupta

2023-05-05 13:48 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/FunctionalTests/WebhookScenarios.cs
Please change file name

2023-05-05 13:49 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/TestConfig.cs
> +        public string SapApiPayloadFileName { get; set; }
Same as above

2023-05-05 13:52 UTC, Sadha1501493 requested changes

2023-05-05 13:52 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/TestConfig.cs
> +        public SapConfiguration SapConfiguration { get; set; }
Same as above

2023-05-05 13:52 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/appsettings.json
> +    "BaseUrl": "https://localhost:65117"
Remove URL

2023-05-05 15:17 UTC, RaviK2233 approved these changes
Reviewed FT and looks good.

2023-05-10 08:20 UTC, jrippington approved these changes
Looks good, thanks!

2023-05-10 09:37 UTC, martyn-fewtrell approved these changes
Looks good

2023-05-10 09:37 UTC, merged