WIP: Feature/77887-FT-scenerio-implementation-change-update-cell
UKHO/erp-facade pull request #35
Opened 2023-05-19 11:34 UTC by prashantmgupta

2023-05-19 12:29 UTC, Sadha1501493 requested changes

2023-05-19 12:29 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/ERPFacadeGeneratedXmlFiles/367ce4a4-1d62-4f56-b359-59e178d78200.xml
Keep this folder empty to download xmls

2023-05-19 12:43 UTC, prashantmgupta commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/SAPXmlHelper.cs
> +        //private static SAPXmlPayload xmlPayload { get; set; }
Done

2023-05-22 09:46 UTC, RaviK2233 reviewed
@Sadha1501493  could you please have a look at the failing checks

2023-05-22 11:47 UTC, RaviK2233 approved these changes
Reviewed FT and all looks good

2023-05-22 14:17 UTC, jrippington approved these changes
Looks good, thanks!

2023-05-22 17:09 UTC, martyn-fewtrell approved these changes
Looks good

2023-05-22 17:09 UTC, merged