81063 - health check
UKHO/erp-facade pull request #39
Opened 2023-05-30 13:36 UTC by kiran1501497

81063 Devops- Health Check

2023-05-31 15:14 UTC, Vishal14583 commented on src/UKHO.ERPFacade.API/Controllers/HealthCheckController.cs
> +        [HttpPost]
```suggestion
        [HttpGet]
```

2023-05-31 15:14 UTC, Vishal14583 commented on src/UKHO.ERPFacade.API/Controllers/HealthCheckController.cs
> +        [HttpPost]
This should be Get request not Post

2023-06-01 06:15 UTC, amogh14893 commented on Deployment/templates/continuous-deployment.yml
small correction in DisplayName - Instead ERP Facade **Webapp** , ERP Facade **API EndPoit**

2023-06-01 06:16 UTC, amogh14893 requested changes
Minor changes in check service status task , Else changes look good to me

2023-06-01 11:05 UTC, amogh14893 approved these changes

2023-06-01 15:05 UTC, jrippington approved these changes
Looks good to me, thanks!

2023-06-01 15:05 UTC, jrippington approved these changes
Looks good to me, thanks!

2023-06-01 16:38 UTC, martyn-fewtrell approved these changes
Looks good

2023-06-02 07:35 UTC, merged