81721 FT-EES Scenario verification with suspend & withdrawn
UKHO/erp-facade pull request #50
Opened 2023-06-15 12:54 UTC by prashantmgupta

2023-06-15 16:33 UTC, Sadha1501493 requested changes

2023-06-15 16:33 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/ERPFacadeScenarioData/Scenario Mapping.xlsx
Please update 'Covered Business' column for appended scenarios.

2023-06-15 16:33 UTC, Sadha1501493 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/SAPXmlHelper.cs
>                      //if (!item.PRODUCTNAME.Equals(product.ProductName))(!product.InUnitsOfSale.Contains(item.PRODUCTNAME)) && (!getUoSInfo(item.PRODUCTNAME).UnitType.Contains("Unit"))
Please removed unused code.

2023-06-16 04:58 UTC, prashantmgupta commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/SAPXmlHelper.cs
> +                    //   AttrNotMatched.Add(nameof(item.PRODUCTNAME));
Resolved

2023-06-16 04:58 UTC, prashantmgupta commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/SAPXmlHelper.cs
>                      if (!item.AGENCY.Equals(product.Agency))
Resolved

2023-06-16 06:59 UTC, prashantmgupta commented on tests/UKHO.ERPFacade.API.FunctionalTests/ERPFacadeScenarioData/Scenario Mapping.xlsx
Updated

2023-06-16 06:59 UTC, prashantmgupta commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/SAPXmlHelper.cs
>                      //if (!item.PRODUCTNAME.Equals(product.ProductName))(!product.InUnitsOfSale.Contains(item.PRODUCTNAME)) && (!getUoSInfo(item.PRODUCTNAME).UnitType.Contains("Unit"))
Resolved

2023-06-16 07:21 UTC, jrippington approved these changes
Looks good

2023-06-16 10:23 UTC, martyn-fewtrell approved these changes
Looks good

2023-06-19 08:00 UTC, RaviK2233 approved these changes
Looks good

2023-06-19 14:45 UTC, merged