84240 shared key authentication
UKHO/erp-facade pull request #52
Opened 2023-06-22 14:30 UTC by Vishal14583

1. Added shared key authentication for ERP facade endpoints.
2. Functional Tests updated accordingly.
3. Unit test cases covered.

2023-06-22 15:12 UTC, RaviK2233 approved these changes
Reviewed FT and looks good

2023-06-23 04:49 UTC, harshal11869 requested changes

2023-06-23 04:49 UTC, harshal11869 commented on tests/UKHO.ERPFacade.API.FunctionalTests/FunctionalTests/PriceChangeScenario.cs
> +        private PriceChangeEndpoint _PriceChange { get; set; }
```suggestion
        private PriceChangeEndpoint _priceChange { get; set; }
```

2023-06-23 04:49 UTC, harshal11869 commented on tests/UKHO.ERPFacade.API.FunctionalTests/Helpers/WebhookEndpoint.cs
>          private readonly RestClient client;
```suggestion
        private readonly RestClient _client;
```

2023-06-23 09:02 UTC, MitaliSingh16 commented on tests/UKHO.ERPFacade.API.FunctionalTests/FunctionalTests/PriceChangeScenario.cs
> +        private PriceChangeEndpoint _PriceChange { get; set; }
Done

2023-06-27 05:39 UTC, shrey1501620 approved these changes

2023-06-27 09:28 UTC, martyn-fewtrell reviewed
Looks good

2023-06-27 09:28 UTC, martyn-fewtrell approved these changes

2023-06-27 09:30 UTC, jrippington approved these changes
Looks good

2023-06-27 09:33 UTC, merged