80330-CleanUpWebjob DevOps Changes
UKHO/erp-facade pull request #56
Opened 2023-06-27 14:30 UTC by kiran1501497

2023-06-27 14:40 UTC, amogh14893 requested changes

2023-06-27 14:40 UTC, amogh14893 commented on azure-pipelines.yml
Can we tweak the order for CleanUpWebJob ? It should be post PriceChangeEventWebjob

2023-06-28 06:01 UTC, kiran1501497 commented on azure-pipelines.yml
I have been completed changes

2023-06-28 06:18 UTC, Vishal14583 approved these changes
LGTM

2023-06-28 11:28 UTC, amogh14893 approved these changes
Reviewed Devops changes , LGTM

2023-06-28 13:06 UTC, martyn-fewtrell approved these changes
Looks good

2023-06-28 13:06 UTC, merged