85650 Configuration changes
UKHO/erp-facade pull request #64
Opened 2023-07-14 05:37 UTC by Nadeem14456

restored EESHealthCheckEnvironmentConfiguration in app settings

2023-07-14 11:07 UTC, jrippington approved these changes
Looks good

2023-07-17 09:41 UTC, Sadha1501493 requested changes

2023-07-17 09:41 UTC, Sadha1501493 commented on Performance Script/config.json
> +    "PriceChangeURL":"/erpfacade/bulkpriceinformation",
Please remove PriceChangeURL

2023-07-17 09:41 UTC, Sadha1501493 commented on Performance Script/config.json
> +    "Token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiI4Y2M0ZGRkNS1kMzdhLTQ5YzItYWQ1NS1iNzU4Mzk
Please remove token value

2023-07-17 09:41 UTC, Sadha1501493 commented on Performance Script/config.json
> +    "Key":"QknDdbIsPT5HmFspsEMnwBUzx2ft7CaemEYFKxQHbhqrTQbNjUZxPWJyEHdZQMVakSth34zyj62EzKC9Wq6gU55R5aCXxrpPEGMFsHU4NVtRXCb8GqkJa9KqgXmWxxyg"
Please remove key value.

2023-07-17 11:54 UTC, MitaliSingh16 commented on Performance Script/config.json
> +    "Key":"QknDdbIsPT5HmFspsEMnwBUzx2ft7CaemEYFKxQHbhqrTQbNjUZxPWJyEHdZQMVakSth34zyj62EzKC9Wq6gU55R5aCXxrpPEGMFsHU4NVtRXCb8GqkJa9KqgXmWxxyg"
Done

2023-07-17 11:55 UTC, MitaliSingh16 commented on Performance Script/config.json
> +    "Key":"QknDdbIsPT5HmFspsEMnwBUzx2ft7CaemEYFKxQHbhqrTQbNjUZxPWJyEHdZQMVakSth34zyj62EzKC9Wq6gU55R5aCXxrpPEGMFsHU4NVtRXCb8GqkJa9KqgXmWxxyg"
Done

2023-07-17 11:55 UTC, MitaliSingh16 commented on Performance Script/config.json
> +    "Token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiI4Y2M0ZGRkNS1kMzdhLTQ5YzItYWQ1NS1iNzU4Mzk
Done

2023-07-17 11:56 UTC, MitaliSingh16 commented on Performance Script/config.json
> +    "PriceChangeURL":"/erpfacade/bulkpriceinformation",
Done

2023-07-17 11:56 UTC, Sadha1501493 approved these changes
Thanks @MitaliSingh16

2023-07-21 08:41 UTC, RaviK2233 approved these changes

2023-07-21 14:48 UTC, harshal11869 approved these changes
Looks Good.

2023-07-21 15:01 UTC, merged