WIP: 98212 LTC json to xml mapping for migrate existing licence
UKHO/erp-facade pull request #85
Opened 2023-10-31 10:44 UTC by sakshi15525

1. Json to xml mapping for migrate existing licence events.
2. Changed attribute 'upn' to 'ecdisManufacturerName' for ros events.
3. Added logging.
4. Added Unit test cases.

2023-10-31 12:46 UTC, pravinvarade10801 approved these changes
LGTM

2023-11-04 13:12 UTC, Vishal14583 commented on tests/UKHO.ERPFacade.EventAggregation.WebJob.Tests/Helpers/RecordOfSaleSapMessageBuilderTests.cs
>          private readonly string jsonForNewLicence1 = @"{""specversion"": ""1.0"",""type"": ""uk.gov.ukho.shop.recordOfSale.v1"",""source"": ""https://uk.gov.ukho.shop"",""id"": ""e744fa37-0c9f-4795-a
Rename all variables to meaningful name.

2023-11-04 13:12 UTC, Vishal14583 requested changes
Rename variables to meaningful names.

2023-11-06 15:09 UTC, Vishal14583 approved these changes
LGTM

2023-11-07 13:31 UTC, kishorambare approved these changes
LGTM.

2023-11-07 15:56 UTC, jrippington approved these changes
Looks good

2023-11-08 08:49 UTC, merged